"use client";
import { useCallback,useEffect,useRef,useState } from "react";
import { askQuestion,checkHealth,deleteSession,forgetMemory,listSessions,myMemories,rememberForMe,sessionHistory,submitFeedback,submitImplicitFeedback,type ChatResult,type DeptRoute,type SessionSummary,type User,type UserMemoryItem } from "@/lib/api";
import Icon from "./Icon"; import styles from "./Chat.module.css";
interface Message { role:"user"|"assistant";content:string;citations?:ChatResult["citations"];error?:boolean;query?:string;rated?:"up"|"down";route?:DeptRoute|null;meta?:Pick<ChatResult,"confidence"|"intent_type"|"verification"|"retrieved_count"|"graph_status"|"graph_evidence_count"> }
const SUGGESTIONS=["暴雨天气下师生应注意哪些安全事项？","心理测评的完整操作流程是什么？","中法学院行李寄存有哪些要求？","研究生开题答辩需要准备什么？"];
function makeSessionId(){return typeof crypto!=="undefined"&&crypto.randomUUID?crypto.randomUUID():Date.now().toString()}
export default function Chat({user,onLogout}:{user:User;onLogout:()=>void}){
 const [messages,setMessages]=useState<Message[]>([]),[input,setInput]=useState(""),[busy,setBusy]=useState(false),[online,setOnline]=useState<boolean|null>(null);
 const [sessionId,setSessionId]=useState<string|null>(null),[sessions,setSessions]=useState<SessionSummary[]>([]),[activeSession,setActiveSession]=useState<string|null>(null),[sidebarOpen,setSidebarOpen]=useState(true);
 const [memoryOpen,setMemoryOpen]=useState(false),[memories,setMemories]=useState<UserMemoryItem[]>([]),[memoryKey,setMemoryKey]=useState("answer_style"),[memoryValue,setMemoryValue]=useState("简洁、分点回答"),[memoryBusy,setMemoryBusy]=useState(false);
 const listRef=useRef<HTMLDivElement>(null),latestUnratedRef=useRef<{query:string;answer:string}|null>(null);
 const welcome=`你好，${user.name}。我会从已生效的制度中检索证据，经 pi Agent 生成与校验后回答，并保留可追溯引用。`;
 useEffect(()=>{checkHealth().then(setOnline)},[]);useEffect(()=>setMessages([{role:"assistant",content:welcome}]),[user.id,welcome]);useEffect(()=>{listRef.current?.scrollTo({top:listRef.current.scrollHeight,behavior:"smooth"})},[messages,busy]);
 const refreshSessions=useCallback(()=>listSessions().then(setSessions).catch(()=>undefined),[]);useEffect(()=>{refreshSessions()},[refreshSessions]);
 const loadMemories=useCallback(()=>myMemories().then(setMemories).catch(()=>undefined),[]);useEffect(()=>{if(memoryOpen)loadMemories()},[memoryOpen,loadMemories]);
 const startNewChat=useCallback(()=>{setSessionId(makeSessionId());setActiveSession(null);setMessages([{role:"assistant",content:welcome}])},[welcome]);
 const loadSession=useCallback(async(sid:string)=>{try{const h=await sessionHistory(sid);setSessionId(sid);setActiveSession(sid);setMessages(h.length?h as Message[]:[{role:"assistant",content:welcome}])}catch{}},[welcome]);
 const removeSession=useCallback(async(sid:string)=>{try{await deleteSession(sid)}catch{}setSessions(s=>s.filter(x=>x.session_id!==sid));if(sid===sessionId)startNewChat()},[sessionId,startNewChat]);
 const send=useCallback(async(forced?:string)=>{const query=(forced??input).trim();if(!query||busy)return;const sid=sessionId??makeSessionId();setMessages(m=>[...m,{role:"user",content:query}]);setInput("");setBusy(true);try{const r=await askQuestion({query,session_id:sid,dept_ids:null});const finalSid=r.session_id||sid;setSessionId(finalSid);setActiveSession(finalSid);setMessages(m=>[...m,{role:"assistant",content:r.answer,citations:r.citations,query,route:r.route,meta:{confidence:r.confidence,intent_type:r.intent_type,verification:r.verification,retrieved_count:r.retrieved_count,graph_status:r.graph_status,graph_evidence_count:r.graph_evidence_count}}]);latestUnratedRef.current={query,answer:r.answer};refreshSessions()}catch(e){setMessages(m=>[...m,{role:"assistant",content:`请求失败：${e instanceof Error?e.message:String(e)}`,error:true}])}finally{setBusy(false)}},[input,busy,sessionId,refreshSessions]);
 const rate=useCallback(async(i:number,signal:"up"|"down")=>{const msg=messages[i];if(!msg||msg.role!=="assistant"||msg.rated||!msg.query)return;setMessages(m=>m.map((x,j)=>j===i?{...x,rated:signal}:x));latestUnratedRef.current=null;try{await submitFeedback({session_id:sessionId||"",query:msg.query,answer:msg.content,signal})}catch{}},[messages,sessionId]);
 const copyAnswer=useCallback(async(m:Message)=>{await navigator.clipboard.writeText(m.content);if(sessionId&&m.query)submitImplicitFeedback({session_id:sessionId,signal:"copy",query:m.query,answer:m.content}).catch(()=>undefined)},[sessionId]);
 useEffect(()=>()=>{const p=latestUnratedRef.current;if(sessionId&&p)submitImplicitFeedback({session_id:sessionId,signal:"abandon",query:p.query,answer:p.answer}).catch(()=>undefined)},[sessionId]);
 async function addMemory(){if(!memoryKey.trim()||!memoryValue.trim())return;setMemoryBusy(true);try{await rememberForMe({key:memoryKey.trim(),value:memoryValue.trim(),category:"preference",consent:true});await loadMemories()}finally{setMemoryBusy(false)}}
 async function removeMemory(id:string){await forgetMemory(id);await loadMemories()}
 const hasConversation=messages.some(m=>m.role==="user");
 return <div className={styles.app}>
  <aside className={`${styles.sidebar} ${sidebarOpen?"":styles.sidebarClosed}`}>
   <div className={styles.sideBrand}><span>兰</span><div><b>i兰</b><small>iLAN CAMPUS QA</small></div></div>
   <button className={styles.newChatBtn} onClick={startNewChat}><Icon name="plus" size={17}/>开启新会话</button>
   <div className={styles.sidebarBody}><div className={styles.sectionTitle}>最近会话 <em>{sessions.length}</em></div>{sessions.length===0&&<div className={styles.empty}>问一个问题，开始积累情景记忆</div>}{sessions.map(s=><div key={s.session_id} className={`${styles.sessionItem} ${activeSession===s.session_id?styles.sessionActive:""}`} onClick={()=>loadSession(s.session_id)}><Icon name="chat" size={14}/><span className={styles.sessionTitle}>{s.title||"新对话"}</span><button onClick={e=>{e.stopPropagation();removeSession(s.session_id)}}><Icon name="trash" size={13}/></button></div>)}</div>
   <button className={styles.memoryEntry} onClick={()=>setMemoryOpen(true)}><span><Icon name="memory" size={17}/></span><div><b>我的长期记忆</b><small>查看系统如何理解你的偏好</small></div><Icon name="arrow" size={14}/></button>
   <div className={styles.sideUser}><div>{user.name.slice(0,1)}</div><span><b>{user.name}</b><small>学生用户 · {user.id}</small></span><button onClick={onLogout}><Icon name="logout" size={15}/></button></div>
  </aside>
  <section className={styles.main}>
   <header className={styles.header}><div className={styles.left}><button className={styles.collapseBtn} onClick={()=>setSidebarOpen(v=>!v)}><Icon name="menu" size={18}/></button><div><b>制度问答工作台</b><small>基于官方文档的可信回答</small></div></div><div className={styles.right}><span className={`${styles.status} ${online?styles.ok:online===false?styles.err:""}`}><i/>{online===null?"连接中":online?"事实与 Agent 服务正常":"后端不可用"}</span><span className={styles.engine}>PI AGENT ENGINE</span></div></header>
   <main className={`${styles.chat} ${!hasConversation?styles.chatEmpty:""}`} ref={listRef}>
    {!hasConversation&&<div className={styles.welcome}><div className={styles.welcomeMark}><Icon name="spark" size={25}/></div><span className={styles.welcomeKicker}>ASK WITH EVIDENCE</span><h1>今天想了解哪项制度？</h1><p>{welcome}</p><div className={styles.suggestions}>{SUGGESTIONS.map((s,i)=><button key={s} onClick={()=>send(s)}><span>0{i+1}</span>{s}<Icon name="arrow" size={14}/></button>)}</div><div className={styles.flow}><span><Icon name="search" size={14}/>混合检索</span><i>→</i><span><Icon name="agent" size={14}/>Agent 生成</span><i>→</i><span><Icon name="shield" size={14}/>可信校验</span><i>→</i><span><Icon name="file" size={14}/>来源引用</span></div></div>}
    {hasConversation&&messages.map((m,i)=><article key={i} className={`${styles.msgRow} ${m.role==="user"?styles.userRow:styles.assistantRow}`}><div className={styles.roleAvatar}>{m.role==="user"?"你":<Icon name="spark" size={17}/>}</div><div className={`${styles.msg} ${m.error?styles.errorText:""}`}><div className={styles.msgHead}><b>{m.role==="user"?"你的问题":"i兰回答"}</b>{m.meta&&<span className={m.meta.verification?.passed?styles.verified:styles.warning}><Icon name="shield" size={13}/>{m.meta.verification?.passed?`已验证 ${Math.round((m.meta.verification.score||0)*100)}%`:"需复核"}</span>}</div><div className={styles.content}>{m.content}</div>
     {m.meta&&<div className={styles.reasoning}><span><Icon name="search" size={13}/>检索 {m.meta.retrieved_count} 条证据</span><span><Icon name="agent" size={13}/>{m.meta.intent_type}</span><span><Icon name="activity" size={13}/>回答置信度 {Math.round((m.meta.confidence||0)*100)}%</span>{m.meta.graph_status&&<span><Icon name="layers" size={13}/>{m.meta.graph_status==="expanded"?"已使用图增强证据":m.meta.graph_status==="no_new_evidence"?"已尝试图增强，未新增证据":m.meta.graph_status==="fallback_unavailable"?"图增强暂不可用，当前为普通 RAG":"未启用图增强"}</span>}</div>}
     {m.meta?.graph_status==="expanded"&&<div className={styles.reasoning}><span><Icon name="layers" size={13}/>图增强新增 {m.meta.graph_evidence_count||0} 条关联证据</span></div>}
     {m.route?.dept_names?.length?<div className={styles.route}><Icon name="building" size={14}/><span>智能路由</span><b>{m.route.dept_names.join("、")}</b><small>{m.route.reasons?.[0]}</small></div>:null}
     {m.citations?.length?<details className={styles.citations}><summary><Icon name="file" size={14}/>查看 {m.citations.length} 条制度依据 <Icon name="arrow" size={13}/></summary><div>{m.citations.map((c,j)=><div key={`${c.doc_id}-${j}`} className={styles.cite}><span>{j+1}</span><div><b>{c.doc_title||c.doc_id}</b><small>{c.section_path?.join(" / ")||`文档切片 #${c.chunk_index}`}</small><p>{c.snippet}</p></div></div>)}</div></details>:null}
     {m.role==="assistant"&&m.query&&!m.error&&<div className={styles.rating}><span>这个回答是否解决了问题？</span><button className={m.rated==="up"?styles.ratedUp:""} onClick={()=>rate(i,"up")} disabled={!!m.rated}>有帮助</button><button onClick={()=>copyAnswer(m)}><Icon name="copy" size={13}/>复制</button><button className={m.rated==="down"?styles.ratedDown:""} onClick={()=>rate(i,"down")} disabled={!!m.rated}>需改进</button></div>}</div></article>)}
    {busy&&<div className={styles.thinking}><span className={styles.thinkingMark}><Icon name="spark" size={17}/></span><div><b>正在协同处理</b><small>路由部门 · 召回事实 · 执行 Agent · 校验引用</small><i><em/><em/><em/></i></div></div>}
   </main>
   <footer className={styles.composer}><div className={styles.composerBox}><textarea value={input} rows={1} placeholder="描述你想咨询的制度、流程或截止时间…" onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();send()}}}/><button onClick={()=>send()} disabled={busy||!input.trim()}><Icon name="send" size={18}/></button></div><p>回答仅依据已生效制度 · 关键结论附带来源 · Shift + Enter 换行</p></footer>
  </section>
  {memoryOpen&&<div className={styles.modalBackdrop} onClick={()=>setMemoryOpen(false)}><section className={styles.memoryPanel} onClick={e=>e.stopPropagation()}><header><div><span>USER SEMANTIC MEMORY</span><h2>我的长期记忆</h2><p>只有你明确同意的低敏偏好会被保存；可随时查看和删除。</p></div><button onClick={()=>setMemoryOpen(false)}>×</button></header><div className={styles.memoryForm}><input value={memoryKey} onChange={e=>setMemoryKey(e.target.value)} placeholder="偏好名称"/><input value={memoryValue} onChange={e=>setMemoryValue(e.target.value)} placeholder="偏好内容"/><button onClick={addMemory} disabled={memoryBusy}>{memoryBusy?"保存中":"记住这个偏好"}</button></div><div className={styles.memoryNotice}><Icon name="shield" size={15}/>身份证、密码、联系方式等敏感信息不会写入长期记忆。</div><div className={styles.memoryList}>{memories.length===0?<div className={styles.memoryEmpty}><Icon name="memory" size={25}/><b>还没有长期记忆</b><small>保存回答风格或稳定偏好后，它会参与后续上下文构建。</small></div>:memories.map(m=><div key={m._id}><span><Icon name="memory" size={15}/></span><div><b>{m.key}</b><p>{String(m.value)}</p><small>{m.category} · revision {m.revision||1}</small></div><button onClick={()=>removeMemory(m._id)}><Icon name="trash" size={14}/></button></div>)}</div></section></div>}
 </div>
}
